[workspace]
resolver = "3"
members = ["oar-scheduler-core", "oar-scheduler-bench", "oar-scheduler-redox", "oar-scheduler-hooks"]

[profile.release]
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "debuginfo"
